### ISSUE TITLE
[Bug Report] Typescript 'vue add vuetify' creates non-functional project

### ISSUE THREAD

**Issue by Deracination** [vuetifyjs/vue-cli-plugin-vuetify#136] opened 2019-11-13 22:51 UTC
### Environment

**Browsers:** Chrome 78.0.3904.97
**OS:** Linux
**vuetify:**  "vuetify": "^2.1.0"
**vue:**  "vue": "^2.6.10"

### Steps to reproduce
- Create new vue typescript project using 'vue create' and choose typescript preset
- cd into project and run 'vue add vuetify'
- yarn run serve

### Expected Behavior
Expect project to compile and run. This worked yesterday before the 2.1.0 vuetify release.

### Actual Behavior
```
ERROR in tester/src/plugins/vuetify.ts(2,21):
2:21 Could not find a declaration file for module 'vuetify/lib'. 'tester/node_modules/vuetify/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/vuetify` if it exists or add a new declaration (.d.ts) file containing `declare module 'vuetify/lib';`
    1 | import Vue from 'vue';
  > 2 | import Vuetify from 'vuetify/lib';
      |                     ^
    3 |
    4 | Vue.use(Vuetify);
    5 |
Version: typescript 3.5.3, tslint 5.20.1
```

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by Deracination** [comment] 2019-11-13 23:30
Adding the 'vuetify' to tsconfig types seems to fix this:
```
"compilerOptions": {
     "types": [
      "vuetify",
      "webpack-env",
      "jest"
    ],

```

**Comment by DRoet** [comment] 2019-11-14 07:40
duplicate of https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/43. stole your title to make it more clear

**Closed by DRoet** 2019-11-14 07:40 UTC
