### ISSUE TITLE
Vuetify does not respect TypeScript in the project

### ISSUE THREAD

**Issue by andreixk** [vuetifyjs/vue-cli-plugin-vuetify#66] opened 2018-12-06 03:15 UTC
When adding vuetify using `vue add vuetify`, the components are added in standards ES6 format regardless of the language used by the project. I create a new project (with `vue create`) to use TypeScript. 
As a result, vuetify components do not get linted with `yarn lint` and throw errors on build.

**Comment by jacekkarczmarczyk** [comment] 2018-12-06 03:16
Please provide exact reproduction steps

**Comment by KaelWD** [comment] 2018-12-06 11:47
Duplicate of #43

> even the <script> tag does not have lang="ts"

vue-cli does not provide a way for us to do this easily. You have to write typescript yourself if you want it.

**Comment by andreixk** [comment] 2018-12-06 11:51
then the vuetify plugin should not replace helloworld.vue and app.vue at all if they're using TS.

**Comment by jacekkarczmarczyk** [comment] 2018-12-06 18:11
I think we should be able to add `lang="ts"` in templates. However the only error/warning related to TS is that `Could not find a declaration file for module 'vuetify/lib'` and it would be there regardless of having `lang="ts"` or not, others are just linting warnings that should be fixed automatically

**Comment by awill2** [comment] 2019-03-31 00:28
+1

**Closed** 2019-05-30 06:02 UTC
