### ISSUE TITLE
[Bug Report] IE11 - syntax error

### ISSUE THREAD

**Issue by ziaxdk** [vuetifyjs/vue-cli-plugin-vuetify#56] opened 2018-11-01 10:17 UTC
### Versions and Environment
**Vuetify:** 1.3.5
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 10

### Steps to reproduce
vue create temp - default
vue add vuetify - default
cd temp
npm run build
http-server ./dist

### Expected Behavior
To work

### Actual Behavior
Syntax error in IE11 console

### Reproduction Link
[https://github.com/ziaxdk/vuetify-cli-bug](https://github.com/ziaxdk/vuetify-cli-bug)

### Other comments
Looks like arrow function are not transpiled into ordinary functions, when "vue add vuetify": 
{render:t=>t(T)}).$mount("#app")}

**Comment by KaelWD** [comment] 2018-11-02 03:00
Duplicate of #55

**Closed by KaelWD** 2018-11-02 03:00 UTC
