### ISSUE TITLE
[Bug Report] Multiple instances of Vue detected in test with Jest and Vuetify

### ISSUE THREAD

**Issue by marc-bouvier** [vuetifyjs/vue-cli-plugin-vuetify#73] opened 2019-01-04 09:29 UTC
### Versions and Environment
**Vuetify:** 1.3.16
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 7

### Steps to reproduce
run unit tests with jest

```
npm run test:unit
```

### Expected Behavior
```
$ npm run test:unit

> vuetify-jest@0.1.0 test:unit D:\Projets\vuetify-jest
> vue-cli-service test:unit

PASS tests/unit/example.spec.js
  HelloWorld.vue
    v matches snapshot (83ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        1.811s
Ran all test suites.
```

### Actual Behavior
```
$ npm run test:unit

> vuetify-jest@0.1.0 test:unit D:\Projets\vuetify-jest
> vue-cli-service test:unit

PASS tests/unit/example.spec.js
  HelloWorld.vue
    v matches snapshot (83ms)

  console.error node_modules/vuetify/dist/vuetify.js:22968
    [Vuetify] Multiple instances of Vue detected
    See https://github.com/vuetifyjs/vuetify/issues/4068

    If you're seeing "$attrs is readonly", it's caused by this

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        1.811s
Ran all test suites.
```

### Reproduction Link
<a href="https://github.com/marc-bouvier/vuetify-jest" target="_blank">https://github.com/marc-bouvier/vuetify-jest</a>

### Other comments
Installed from vue-cli plugins only.
No configuration was changed manually.

Vue-cli plugins used : 

Vue-cli 3.0.5
@vue/cli-service 3.2.3
@vue/cli-plugin-babel 3.2.2
@vue/cli-plugin-eslint 3.2.2
@vue/cli-plugin-unit-jest 3.2.3
vue-cli-plugin-editorconfig 0.2.1
vue-cli-plugin-i18n 0.5.1
vue-cli-plugin-vuetify 0.4.6

**Comment by KaelWD** [comment] 2019-01-05 05:03
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4964

**Closed by KaelWD** 2019-01-05 05:03 UTC
